version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: blockchain-explorer-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: blockchain_explorer
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blockchain-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blockchain-explorer-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/blockchain_explorer?authSource=admin
      RPC_URL: ${RPC_URL}
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - blockchain-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blockchain-explorer-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - blockchain-network

  redis:
    image: redis:7-alpine
    container_name: blockchain-explorer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blockchain-network

volumes:
  mongodb_data:
  redis_data:

networks:
  blockchain-network:
    driver: bridge